name: test pipeline CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    
    - name: make unit-tests
      run: make unit-test

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with: 
        name: test_artifact
        path: bin/tests
        
    - name: Running test
      run: |
        chmod +x bin/tests
        bin/tests
      shell: bash
